version: 1

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=github.com/greenstevester/gh-aca-utils
  mod: mod

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -tags=nodbus
    goos:
      - android
      - freebsd
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w
      - -X github.com/greenstevester/gh-aca-utils/cmd.Version={{.Version}}
      - -X github.com/greenstevester/gh-aca-utils/cmd.Commit={{.Commit}}
      - -X github.com/greenstevester/gh-aca-utils/cmd.Date={{.CommitDate}}
      - -X github.com/greenstevester/gh-aca-utils/cmd.BuiltBy=goreleaser
    # Skipping builds for Android non-ARM64 architectures as they need CGO enabled
    # https://goreleaser.com/limitations/cgo/
    ignore:
      - goos: android
        goarch: "386"
      - goos: android
        goarch: amd64
      - goos: android
        goarch: arm

archives:
  - formats:
      - binary
    name_template: "gh-aca-utils_{{ .Tag }}_{{ .Os }}-{{ .Arch }}{{if .Arm}}_{{.Arm}}{{end}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"